### ISSUE TITLE
Error 500 with cli-python and dynamic Infrastructure (Pipeline yaml Azure DevOps)

### ISSUE THREAD

**Issue by bcouavoux** [Neotys-Labs/neoload-cli#95] opened 2020-09-24 08:13 UTC
Hello,
We have a number of issues with setting up yaml pipeline to launch our load shots on a kubernetes cluster. Our Kubernetes cluster is correctly configured as dynamic infrastructur in neoload web.

**We use exaclty the same pipeline than ur example :**

`- task: Bash@3
    displayName: Install NeoLoad
    continueOnError: false
    inputs:
      targetType: 'inline'
      script: |
        pip install neoload
        neoload --version
  - task: Bash@3
    displayName: Configure the NeoLoad test
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
         neoload login --url ${{parameters.neoloadApiUrl}} ${{parameters.neoloadToken}} \
                test-settings --zone ${{parameters.zoneId}} --lgs ${{parameters.lgs}} --scenario sctest patch "poc-test" \
                project --path project_poc/ upload "poc-test"

  - task: Bash@3
    displayName: Run the NeoLoad test
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
        neoload run \
             --name "TestLaunchedFromAzureCI_build_$(Build.BuildNumber)" \
             --description "Azure example with meta; $(Build.BuildUri)" \
             "poc-test"`

**When we launch the pipeline, we have first several error during the configuration step :**

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.5/x64/bin/neoload", line 11, in <module>
    load_entry_point('neoload==1.1.3', 'console_scripts', 'neoload')()
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/neoload/commands/project.py", line 20, in cli
    upload(path, name_or_id)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/neoload/commands/project.py", line 33, in upload
    neoLoad_project.upload_project(path, get_endpoint(settings_id))
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/neoload/neoload_cli_lib/neoLoad_project.py", line 50, in upload_project
    display_project(rest_crud.post_binary_files_storage(endpoint, file, filename))
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/neoload/neoload_cli_lib/rest_crud.py", line 97, in post_binary_files_storage
    response = requests.post(__create_url_file_storage(endpoint), headers=__create_additional_headers(),
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/neoload/neoload_cli_lib/rest_crud.py", line 17, in request_patch
    return slf.request_orig(*args, **kwargs, timeout=timeout)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='neoload-files.saas.neotys.com', port=443): Read timed out. (read timeout=5)

**After that, during the run step, the dynamic infrastructure starting well. The controler and the load generator are correctly configured and start well. But we have a problem with downloading project to the controler :**

![image](https://user-images.githubusercontent.com/52322253/94117635-c4be5900-fe4c-11ea-8959-5aee934c5575.png)
![image](https://user-images.githubusercontent.com/52322253/94118935-7c079f80-fe4e-11ea-8c05-da4fe55bdd4c.png)

**The controller on kubernetes cluster log :**

2020/09/18 10:33:24 INFO  - neoload.controller.agent.ControllerAgent: Stopped connection to URL: https://neoload-api.saas.neotys.com on Zone: KzHpZ
2020/09/18 10:33:24 INFO  - neoload.controller.agent.ControllerAgent: Controller is stopped
2020/09/18 10:33:24 INFO  - neoload.controller.agent.ControllerAgent: Controller Agent Status changed to: BUSY
2020/09/18 10:33:24 INFO  - neoload.controller.agent.ControllerAgent: Controller is stopping
2020/09/18 10:33:08 [RxNewThreadScheduler-3] ERROR com.neotys.nlweb.resources.definition.api.a.d - An error occurred while processing callback for order NEOLOAD_CONTROLLER_AGENT_DOWNLOAD_PROJECT on this resource side
java.lang.IllegalArgumentException: Could not download file. Status code was not 200, got: 500
 at com.neotys.nl.controller.agent.b.m.a(m.java:73)
 at com.neotys.nl.controller.agent.b.m.a(m.java:55)
 at com.neotys.nl.controller.agent.b.i.a(i.java:187)
 at com.neotys.nl.controller.agent.c.c.a(c.java:40)
 at com.neotys.nlweb.resources.definition.api.a.d.a(d.java:65)
 at com.neotys.nlweb.resources.definition.api.a.d.a(d.java:50)
 at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
2020/09/18 10:33:08 ERROR - neoload.controller.agent.ControllerAgent: Could not download file. Status code was not 200, got: 500
2020/09/18 10:33:07 INFO  - neoload.controller.agent.ControllerAgent: Controller Agent Status changed to: BUSY_DOWNLOADING_PROJECT
2020/09/18 10:32:26 INFO  - neoload.controller.agent.ControllerAgent: Successfully connected to URL: https://neoload-api.saas.neotys.com on Zone: KzHpZ
2020/09/18 10:32:26 INFO  - neoload.controller.agent.ControllerAgent: Try to register to URL: https://neoload-api.saas.neotys.com 
2020/09/18 10:32:26 INFO  - neoload.controller.agent.ControllerAgent: Controller Agent Status changed to: BUSY
2020/09/18 10:32:26 INFO  - neoload.controller.agent.ControllerAgent: Connection test to NeoLoad Web successful.
2020/09/18 10:32:25 INFO  - neoload.controller.agent.ControllerAgent: Testing connection to NLWeb... URL: https://neoload-api.saas.neotys.com Zone: KzHpZ
2020/09/18 10:32:24 INFO  - neoload.controller.agent.ControllerAgent: Starting controller agent (7.5.1 build=20200909-44)...
2020/09/18 10:32:24 INFO  - neoload.controller.agent.ControllerAgent: JVM Version:BellSoft - 1.8.0_252 - OpenJDK 64-Bit Server VM - Xmx= 2224029696 bytes
2020/09/18 10:32:24 INFO  - neoload.controller.agent.ControllerAgent: OS Version:amd64 - Linux - 4.15.0-1092-azure

**Comment by stephanemartin** [comment] 2020-09-24 10:11
The issue is  "neoload-files.saas.neotys.com 443 Read timed out." 

Which size is your zip file ?

**Comment by bcouavoux** [comment] 2020-09-24 10:33
The zip file is 126MO. I just checked and there is several file that is not necessary...
I will delete all the not necesary files, re launch the pipeline and keep u informed.

What is the size of a "normal" zip ?

**Comment by guillaumebert** [comment] 2020-09-24 13:35
There is no "normal" size for the zip. But it seems the CLI had  a too short timeout that seems to prevent the file for being successfully uploaded.
A  fix is merged, and will be released on pypi soon.

**Comment by stephanemartin** [comment] 2020-09-25 07:48
The limit of project size is 250Mo for SaaS.

**Comment by stephanemartin** [comment] 2020-09-25 09:32
Please try new release 1.1.4 and reopen this issue if you have the same error.

**Closed by stephanemartin** 2020-09-25 09:32 UTC
