### ISSUE TITLE
AttributeError trying to run on local docker infrastructure

### ISSUE THREAD

**Issue by ts-sean-foley** [Neotys-Labs/neoload-cli#186] opened 2021-12-02 18:05 UTC
I fumbled my way through some of the example commands, trying to just get it to run the example test in a dev setting. I believe I have my environment set up.  There were a few inconsistencies in the command examples, for example I am thinking the upload command in the docker example expects a test id as a parameter and gives an error of "No id associated with the name 'run'" when executed as the specified chain. When I figured out my way around that, I am now getting the AttributeError described below:
```
Traceback (most recent call last):
  File "/usr/local/bin/neoload", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1696, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/neoload/commands/run.py", line 44, in cli
    hooks.trig("test.start", test_settings_json)
  File "/usr/local/lib/python3.9/site-packages/neoload/neoload_cli_lib/hooks.py", line 13, in trig
    module = getattr(module, comp)
AttributeError: module 'neoload_cli_lib' has no attribute 'docker_lib'
```
Is some step missing from my environment or does this seem like an incompatibility or a bug?

**Comment by stephanemartin** [comment] 2021-12-03 15:12
Hello,
How do you have produced this error ?
Because it says that docker_lib is missing and the file is present in pypi package.

Best regards,
Stephane.

**Comment by ts-sean-foley** [comment] 2021-12-04 01:01
I actually did not install using the pypi package but followed some git steps to download this repo and install posted on a neotys blog entry. I have already tried neoload docker uninstall and docker up. Will try a few more variations and report back. The docker_lib.py file is definitely there in the neload_cli_lib directory so I am thinking it might be python version or something else unusual.

**Comment by stephanemartin** [comment] 2021-12-06 10:48
Thank you for your feedback.
We reproduce now, we are investigating why.

We will fix the doc.

Best regards.

**Comment by stephanemartin** [comment] 2023-01-20 09:39
Fixed with https://github.com/Neotys-Labs/neoload-cli/pull/210

**Closed by stephanemartin** 2023-01-20 09:39 UTC
Labels: bug, documentation
